package business

type RouterGroup struct {
	// Code generated by github.com/zouchangfu/QanLong Begin; DO NOT EDIT.
	DetectTaskResult
	Task
	// Code generated by github.com/zouchangfu/QanLong End; DO NOT EDIT.
}
