package {{ .PackageName }}


type ServiceGroup struct {
    // Code generated by github.com/zouchangfu/QanLong Begin; DO NOT EDIT.

	// Code generated by github.com/zouchangfu/QanLong End; DO NOT EDIT.
}

