package business

import "github.com/zouchangfu/QanLong/service"

type ApiGroup struct {
	// Code generated by github.com/zouchangfu/QanLong Begin; DO NOT EDIT.
	Task
	// Code generated by github.com/zouchangfu/QanLong End; DO NOT EDIT.
}

var (
	detectTaskService = service.ServiceGroupApp.DetectTaskServiceGroup.TaskService
)
